FORMAT: 1A
HOST: https://webapps.vlp.com/

# VLP v1

Service Oriented Architecture specified for the VLP project.

# VLP [/]

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

Dates are always specified as `yyyy-mm-dd`, times as `HH:mm:ss:SSS`, according to
[Java SimpleDateFormat](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html).

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "profile_url": "/profiles",
            "selections_url": "/selections/my",
            "events_url": "/events",
            "products_url": "/products",
            "documents_url": "/documents",
            "ar_url": "/ar",
            "contacts_url": "/contacts"
        }

+ Response 500
    Returned when a generic error occours.

    + Body


######################
# Group IS00 - Session
######################

This group allows the user to interact with its current session objects.

## Session [/session]

+ Attributes (Session Base)

### Read Session [GET]

+ Response 200 (application/json)

    + Attributes (Session)

+ Response 500
    Returned when a generic error occours.

    + Body

### Upsert Session [PUT]

Create or update objects in current user session.

+ Request (application/json)
    + Attribute (Session)

+ Response 200

    + Headers

            Location: /events/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



#######################
# Group IS01 - Profiles
#######################

Resources related to user's profile in the API.

## Profiles collections [/profiles{?consultantId}{?page}]

+ Attributes (Collection)
  + profiles (array[Profile]) - array of user accessible profiles

### List Profiles [GET]
List user profiles. This can be sliced and filtered in order to return only
profiles associated with a given `consultantId`.

+ Parameters
    + page: 1 (optional, number) - The page of profiles to return
    + consultantId: 1 (optional, number) - ID of the consultant associated with this user

+ Response 200 (application/json)

    + Headers

            Link: </profiles?page=2>; rel="next"

    + Attributes (Profiles collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Profile [POST]
Create a user profile.


+ Request (application/json)
    + Attributes (Profile Create)

+ Response 201

    + Headers

            Location: /profiles/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Profile [/profiles/{id}]

+ Parameters
    + id: 1 (required, number) - ID of the user

+ Attributes (Profile Base)
    + id: 1 (required, number) - ID of the user profile

### Read Profile [GET]

+ Response 200 (application/json)

    + Attributes (Profile)
      + id: 1 (required, number) - ID of the user profile
      + password: null (string) - password of the user profile. This field will be null

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Profile [PUT]

+ Request (application/json)

    + Attributes (Profile Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Profile [DELETE]

+ Response 204


+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## User personal profile [/profiles/my]

Used to retrieve user personal details.

### Read Profile [GET]

+ Response 200 (application/json)
  + Attributes (Profile)
      + id: 1 (required, number) - ID of the user profile
      + password: null (string) - password of the user profile. This field will be null

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Profile Addresses collections [/profiles/{userId}/addresses{?page}]

+ Attributes
  + count: 1 (number) - total number of addresses
  + addresses (array[Profile Address]) - array of user addresses

### List Profile Addresses [GET]

+ Parameters
  + userId: 1 (required, number) - ID of the user
  + page: 1 (optional, number) - The page of addresses to return

+ Response 200 (application/json)

      + Headers

              Link: </profiles/1/addresses?page=2>; rel="next"

      + Attributes (Collection)
        + addresses(array[Address1,Address2,Address3])

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Profile Address [POST]

+ Request (application/json)
    + Attribute (Profile Address Create)

+ Response 201

    + Headers

            Location: /profiles/1/addresses/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Profile Address [/profiles/{userId}/addresses/{id}]

+ Parameters
    + userId: 1 (number) - ID of the user
    + id: 1 (number) - ID of the address

+ Attributes (Profile Address Base)
    + id: 1 (required, number) - ID of the address

### Read Profile Address [GET]

+ Response 200 (application/json)

    + Attributes (Profile Address)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Profile Address [PUT]

+ Request (application/json)

    + Attributes (Profile Address Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Profile Address [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



#########################
# Group IS15 – Selections
#########################

Resources related to user's selected products.
An user can list its selected products, create a selection for his session and then edit it.

**Note**: Only one product per category (e.g. serramenti, pavimenti) can be selected
at a given time. If another product of the same category is selected, it will replace
the currently selected product.

## Selections collections [/selections/]

The following methods allow the user to interact with selected products.

+ Attributes
    + selections (array[Selection]) - selections perfomed by the user

### List Selections [GET]

This action retrieves the list of selected products.

+ Response 200 (application/json)

    + Attributes (Selections collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Selection [POST]

This action is used to create a new selection in the user's selection object.
It will replace his current selection if he already has one in the same category.

+ Request (application/json)

  + Attributes (Selection Write)

+ Response 201

    + Headers

            Location: /selections/serramenti

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Selection [/selections/{type}]

These actions operate on the selection of the required `type`.

+ Parameters
    + type: serramenti (string) - type of selection to operate on. Each selection is a category (e.g. `serramenti`, `pavimenti`).

### Read Selection [GET]

+ Response 200 (application/json)

    + Attributes (Selection)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Selection [PUT]

+ Request (application/json)

    + Attributes (Selection Write)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Selection [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


########################
# Group IS03 - Documents
########################

Resources related to user's documents in the API.
An user can list its previous documents, create a document and then edit it.

Document acts as a "super-class" for quotes and orders.

## Documents collections [/documents{?userId}{?page}{?type}]

The following methods allow the user to interact with documents.

+ Attributes (Collection)
    + documents (array[Document]) - array of documents accessible by the user

### List Documents [GET]

This action retrieves the list of documents accessible by the user,
possibly sliced and filtered only for the specified `userId` and/or `type`.

+ Parameters
    + userId: 1 (optional, number) - Filter documents created by the specified `userId`.
    + page: 1 (optional, number) - The page of documents to return.
    + type: quote (optional, enum[string]) - Filter only specified type of document.
        + Members
            + quote
            + order

+ Response 200 (application/json)

    + Headers

            Link: </documents?page=2>; rel="next"

    + Attributes (Documents collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Document [POST]

This method allows the user to create a new document.

If no `userId` is given, it is assumed that the document is created for the current user.

**Note**: the returned `Location` header points to the created document ID,
not the given FP Dealer ID.

+ Request (application/json)
    + Attributes (Document Create)

+ Response 201

    + Headers

            Location: /documents/2

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Document [/documents/{id}]

+ Parameters
    + id: 1 (required, string) - ID of the document

+ Attributes (Document Base)
    + id: 1 (required, number) - ID of the document

### Read Document [GET]

See the details of a given document. This returns the single document
istances with its historic statuses.

+ Response 200 (application/json)

    + Attributes (Document Read)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Document [PUT]

This action allows the user to change an existing document.

**Note**: When the current status of a document is changed, its historic
statuses will have to be recorded. Manual changes on historic statuses are not
supported.

+ Request (application/json)
    + Attributes (Document Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Document [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Document Files collections [/documtents/{id}/files]

### Create Document File [POST]

This actions allow adding a new file to an existing document.

+ Request (application/json)
    + Attributes (Document File Create)

+ Response 201

    + Headers

            Location: /documents/2/files/pdf

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Document File [/documents/{id}/files/{format}]

API route for interacting with documents' files.

Create and update actions expect the file stream as input.

**Note**: when the available files change (CD actions) also the available
`formats` field on the document will get updated.

+ Parameters
    + id: 1 (required, string) - ID of the document
    + format: pdf (required, string) - format of the file with which we're interacting

+ Attributes (Document File Base)
    + id: 1 (required, number) - ID of the document

### Read Document File [GET]
Retrieve the document (file stream).

+ Response 200 (application/stream)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Document File [PUT]

+ Request (application/json)
    + Attributes (Document File Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Document File [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



#####################
# Group IS12 - Events
#####################

## Events collections [/events{?userId}{?page}{?type}{?contentType}]

+ Attributes (Collection)
    + events (array[Event]) - array of returned events

### List Events [GET]

Retrive content (e.g. stories, products) events, possibly filtered by `userId`
and/or `type` and sliced.

+ Parameters
    + userId: 1 (optional, number) - Filter events created by the specified user
    + type: vote (enum[string]) - Filter only specified type of event
        + Members
            + view - content visualization
            + vote - content up or down vote
            + desire - content desired
    + contentType: story (optional, enum) - Filter only events with the specified content type
    + page: 1 (optional, number) - The page of events to return

+ Response 200 (application/json)

    Response with multiple like events.

    + Headers

            Link: </events?page=2>; rel="next"

    + Attributes (Collection)
        + events (array[Event1, Event2, Event3, Event1, Event2, Event3, Event1, Event2, Event3])

+ Response 500
    Returned when a generic error occours.

    + Body

### Find Events [GET /events/find{?contentId}{?type}{?sku}]

Action that can be used to find the last event in the repository starting
from a contentId or sku

Action return an array that contains all events linked at contentId.

+ Parameters
    + contentId: 1 (string) - ID of the content
    + type: vote (enum[string]) - Filter only specified type of event
        + Members
            + view - content visualization
            + vote - content up or down vote
            + desire - content desired
    + sku: 0001 (string) - ID of the sku

+ Response 200 (application/json)
    + Attributes (Events collections)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Upsert Event [POST /events/upsert]

Action that can be used to insert and/or update the events of type view in the repository associated
at a contentId and a date.

If the event not exists it'll created, else it'll be updated

+ Request (application/json)
    + Attribute (Event Create)

+ Response 200

    + Headers

            Location: /events/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Event [POST]

+ Request (application/json)
    + Attribute (Event Create)

+ Response 201

    + Headers

            Location: /events/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Event [/events/{id}]

+ Attribute (Event Base)
    + id: 1 (required, number) - ID of the event

+ Parameters
    + id: 1 (required, string) - ID of the event

### Read Event [GET]

+ Response 200 (application/json)
    + Attributes (Event)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Event [PUT]

Updating an "event" is a weird idea. Yet it makes sense when an event is
intended as a user action (e.g. like/dislike). For instance, a user can first
like a content (creating an event on the specified content) and then dislike it,
updating his previous event.

+ Request (application/json)
    + Attributes (Event Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Event [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



#######################
# Group IS17 - Products
#######################

API group used to handle products.

## Products collections [/products]

+ Attributes (Collection)
    + products (array[Product]) - array of products accessible by the user

### Find products [GET /find{?commerceSKU}{?attributes}]

Action that can be used to find a product in the repository starting
from the commerce SKU and the selections (map of attributes).

This action can be used to retrieve the Product repository ID that can later be used to
retrieve images and renderings.

Only one Product is exptected to be returned, but for consistency with other
collection actions we return an array.

+ Parameters
    + commerceSKU: 1 (string) - SKU on the commerce
    + attributes: {"color": "black", "isolation": "high", "material": "wood"} (object) -
      attribute selection on the commerce SKU product

+ Response 200 (application/json)
    + Attributes (Products collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Product [POST]

+ Request (application/json)
    + Attribute (Product Create)

+ Response 201

    + Headers

            Location: /products/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Product [/products/{id}]

+ Attributes (Product Base)
    + id: 5 (required, string) - SKU of the product in the product repository

+ Parameters
    + id: 5 (required, string) - SKU of the product

### Read Product [GET]

+ Response 200 (application/json)
    + Attributes (Product)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Product [PUT]

+ Request (application/json)
    + Attributes (Product Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Product [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

#############################
# Group IS02 - Product Images
#############################

Sub-resource of a product resource. First find the product SKU, then interact
with its images.

## Product Images collections [/products/{productId}/images]

+ Parameters
    + productId: 1 (required, number) - SKU on the product repository


### Create Product Image [POST]

+ Request (application/json)

    + Attributes (Product Image Write)

+ Response 201

    + Headers

            Location: /products/{productId}/images/main

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


## Product Image [/products/{productId}/images/{type}/{?index}]

+ Parameters
    + type: main (required, enum[string]) - type of the image being required.
        + Members
            + main
            + banner
            + carousel
            + details
    + productId: 1 (required, string) - SKU on the product repository.
    + index: 1 (number) - for image lists (e.g. carousels) the index of the image.

### Read Product Image [GET]
Retrieve the image (file stream).

+ Response 200 (image/png)
    + Attributes (Product Image)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


### Update Product Image [PUT]

+ Request (application/json)
    + Attributes(Product Image Write)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Product Image [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



############################
# Group IS08 - Asset Bundles
############################

Assets used in the 3D viewer application. An asset is ultimately a file,
identified by the pair (`type`, `name`). Assets are used to represent static
resources in the 3D Viewer, such as models, finishings and parts of products,
surfaces and scenes.

## Asset Collections [/assets]

### Create Asset [POST]

+ Request (application/json)
    + Attributes (Asset Write)

+ Response 201

    + Headers

            Location: /assets/model/name

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Asset [/assets/{type}/{name}]

+ Parameters
    + type: model (enum) - type of the asset bundle
        + Members
            + model
            + finishing
            + part
    + name (string) - name of the asset bundle

+ Attributes (Asset Base)

### Read Asset [GET]
Retrieve the image (file stream).

+ Response 200 (application/png)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Asset [PUT]

+ Request (application/json)
    + Attributes (Asset Write)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Asset [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


#################
# Group IS09 - 3D
#################

API group used to handle objects managed by the augmented reality 3D viewer.

The main resources managed are:

+ `Object`, an object rendered in a 3D environment
+ `Scene`, a 3D environment consisting of multiple objects
+ `Surface`

## Scenes collections [/ar/scenes{?userId}{?page}]

+ Attributes (Collection)
    + scenes (array[Scene]) - array of scenes accessible by the user

### List Scenes [GET]

+ Parameters
    + userId: 1 (optional, number) - filter scenes for the specified user
    + page: 1 (optional, number) - slice scenes

+ Response 200 (application/json)

    + Attributes (Scenes collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Copy Scene from set [POST /ar/scenes/copy]

This action creates a new scene copying an existing set (scene template). In then
proceeds to create a new Scene Object for the specified productId and associates
it with the newly created scene.

+ Request (application/json)
    + Attributes
        + productId (required, number) - SKU of the product in the repository
        + default_set (required, string)

+ Response 201

    + Headers

            Location: /ar/scenes/1

### Create Scene [POST]

+ Request (application/json)
    + Attributes (Scene Create)

+ Response 201

    + Headers

            Location: /ar/scenes/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Scene [/ar/scenes/{id}]

+ Attributes (Scene Base)
    + id: 1 (required, string) - ID of the scene.

+ Parameters
    + id: 1 (string) - ID of the scene.

### Read Scene [GET]

+ Response 200 (application/json)

    + Attributes (Scene)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Scene [PUT]

+ Request (application/json)

    + Attributes (Scene Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Scene [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Objects collections [/ar/scenes/{sceneId}/objects{?page}]

+ Attributes (Collection)
    + objects (array[Object]) - array of objects accessible by the user

+ Parameters
    + sceneId: 1 (string) - scene owning the objects

### List Objects [GET]

+ Parameters
    + page: 1 (optional, number) - slice scene objects

+ Response 200 (application/json)
    + Attributes (Objects collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Object [POST]
Create a new Object. If `sceneId` is specified, it is implied that the object
will also be "added" to the scene.

+ Request (application/json)
    + Attributes (Object Create)

+ Response 201

    + Headers

            Location: /ar/objects/3

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Object [/ar/scenes/{sceneId}/{id}]

+ Attributes (Object Base)
    + id: 1 (required, string)

+ Parameters
    + id: 1 (string) - ID of the object
    + sceneId: 1 (string) - scene owning the objects

### Read Object [GET]

+ Response 200 (application/json)

    + Attributes (Object)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Object [PUT]

+ Request (application/json)

    + Attributes (Object Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Object [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


## Surfaces collections [/ar/scenes/{sceneId}/surfaces{?page}]

+ Attributes (Collection)
    + surfaces (array[Surface]) - array of surfaces accessible by the user

### List Surfaces [GET]

+ Parameters
    + sceneId: 5 (required, number) - ID scene
    + page: 1 (number) - slice surfaces


+ Response 200 (application/json)

    + Headers

            Link: </ar/scenes/1/surfaces?page=2>; rel="next"

    + Attributes (Surfaces collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Surface [POST]

+ Request (application/json)
    + Attribute (Surface Create)

+ Response 201

    + Headers

            Location: /ar/scenes/1/surfaces/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Surface [/ar/scenes/{sceneId}/surfaces/{id}]

+ Attributes (Surface Base)
    + id: 1 (number) - ID of the surface

+ Parameters
    + sceneId: 5 (required, number) - ID scene
    + id: 1 (required, string) - ID of the surface

### Read Surface [GET]

+ Response 200 (application/json)
    + Attribute (Surface)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Surface [PUT]

+ Request (application/json)
    + Attribute (Surface Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Surface [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



###############################
# Group IS07 - Contact Requests
###############################

API group used to handle users' contact requests.

## Contacts collections [/contacts{?userId}{?page}]

+ Attributes (Collection)
  + contacts (array[Contact]) - array of contact requests accessible by the user

### List Contacts [GET]

+ Parameters
    + userId: 1 (optional, string) - filter contact requests for the specified user
    + page: 1 (optional, number) - slice contact requests


+ Response 200 (application/json)
    + Attributes (Contacts collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Contact [POST]

+ Request (application/json)
    + Attributes (Contact Create)

+ Response 201

    + Headers

            Location: /contacts/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Contact [/contacts/{id}]

+ Parameters
    + id: 1 (required, string) - ID of the contact request with which interact

+ Attributes (Contact Base)
    + id: 1 (required, number)

### Read Contact [GET]

+ Response 200 (application/json)
    + Attributes (Contact)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Contact [PUT]

+ Request (application/json)
    + Attributes (Contact Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Contact [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



##############################
# Group IS18 - Wishlist Groups
##############################

API group used to handle groups of wishlists.

## Wishlist Groups collections [/wishlists{?userId}{?page}]

+ Attributes (Collection)
    + wishlists (array[Wishlist1, Wishlist2, Wishlist3]) - array of wishlist groups accessible by the user

### List Wishlist Groups [GET]

This action retrieves the list of wishlists groups accessible by the user,
possibly sliced and filtered only for the specified `userId`.

+ Parameters
    + userId: 1 (optional, number) - Filter wishlist groups created by the specified `userId`.
    + page: 1 (optional, number) - The page of wishlist groups to return.

+ Response 200 (application/json)
    + Attributes (Wishlist Groups collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Wishlist Group [POST]

+ Request (application/json)
    + Attribute (Wishlist Group Create)

+ Response 201

    + Headers

            Location: /wishlists/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Wishlist Group [/wishlists/{id}]

+ Attributes (Wishlist Group Base)
    + id: 5 (required, string) - id of the wishlist group

+ Parameters
    + id: 5 (required, string) - id of the wishlist group

### Read Wishlist Group [GET]

+ Response 200 (application/json)
    + Attributes (Wishlist Group)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Wishlist Group [PUT]

+ Request (application/json)
    + Attributes (Wishlist Group Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Wishlist Group [DELETE]

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Wishlist Group Events Collections [/wishlists/{id}/events{?userId}{?page}{?contentType}]

+ Parameters
    + id: 5 (required, string) - id of the wishlist group

+ Attributes (Collection)
    + events (array[Wishlist Group Event]) - array of `desire` events associated with the given wishlist

### List Wishlist Group Events [GET]

This action retrieves the events of type `desire` associated with the given
wishlist group id.

+ Parameters
    + userId: 1 (optional, number) - Filter wishlist groups created by the specified `userId`.
    + page: 1 (optional, number) - The page of wishlist group events to return.
    + contentType: story (optional, enum) - Filter only events with the specified content type

+ Response 200 (application/json)

    + Attributes (Wishlist Group Events Collections)
        + type: desire

### Add Event to Wishlist Group [POST]

+ Request (application/json)
    + Attribute (Wishlist Group Event Create)

+ Response 201

    + Headers

            Location: /wishlists/1/events/5

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Wishlist Group Event [/wishlists/{groupId}/events/{id}]

+ Attributes (Wishlist Group Event Base)
    + groupId: 5 (required, string) - id of the wishlist group

+ Parameters
    + groupId: 2 (required, number) - id of the wishlist group
    + id: 5 (required, string) - id of the wishlist group event

### Delete Event from Wishlist Group [DELETE]
This removes an event from a wishlist group. It does not delete the event.

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

# Data Structures

## Collection (object)
+ count: 1 (number) - total number of resources that can be accessed by the user

## Session Base (object)
+ area: Milano (string) - current user selected area
+ domain: Moda (string) - current user selected domain

## Profile Base (object)
+ consultantId: 1 (number) - ID of the consultant associated with this user
+ email: `v.ponte@wintech.it` (required, string)
+ username: `v.ponte@wintech.it` (string) - the field isn't null when user is registered and validated
+ password: `password` (required, string) - the field isn't null when user is registered
+ firstName: Valerio (string)
+ lastName: Ponte (string)
+ phoneNumber: `0039-3401004285` (string) - A string with the following format: `<4 digits country code>-<phone number>`
+ imageUrl: `http://lnx.flushyourlife.com/voilap/dist/images/autore.png` (string) - user profile image
+ description: Editor, Open Innovator, Cyber Anthropologist and Blogger. (string)
+ area: Milano (string) - position shared by the user
+ address: Via Giuseppe Garibaldi 16 (string) - Main user address
+ city: Milano (string) - Main user addresss
+ status (enum) - Whether the user activated the account or not
    + active
    + inactive

## Profile Base Partial (object)
+ consultantId: 1 (number) - ID of the consultant associated with this user
+ email: `v.ponte@wintech.it` (required, string)
+ username: `v.ponte@wintech.it` (string) - the field isn't null when user is registered and validated
+ password: `password` (string) - the field isn't null when user is registered
+ firstName: Valerio (string)
+ lastName: Ponte (string)
+ phoneNumber: `0039-3401004285` (string) - A string with the following format: `<4 digits country code>-<phone number>`
+ imageUrl: `http://lnx.flushyourlife.com/voilap/dist/images/autore.png` (string) - user profile image
+ description (string)
+ area: Milano (string) - position shared by the user
+ address (string) - Main user address
+ city (string) - Main user addresss
+ status (enum) - Whether the user activated the account or not
    + active
    + inactive

## Profile Create (Profile Base)
+ image: `R0lGODlhEAAOALMAAOazToeHh0tLS/7LZv/0jvb29t/f3//Ub//ge8WSLf/rhf/3kdbW1mxsbP//mf///yH5BAAAAAAAL` (string) - serialized stream (base64) representing the image.

## Profile Update (Profile)
+ image: `R0lGODlhEAAOALMAAOazToeHh0tLS/7LZv/0jvb29t/f3//Ub//ge8WSLf/rhf/3kdbW1mxsbP//mf///yH5BAAAAAAAL` (string) - serialized stream (base64) representing the image.

## Profile Address Partial Base (object)
+ userId: 1 (required, number) - ID of the user owning this address
+ zipCode: 20158 (required, number)
+ country: Italia (required, string)
+ city: Milano (required, string)
+ province: MI (required, string)
+ phoneNumber: `0039-3401004285` (string) - A string with the following format: `<4 digits country code>-<phone number>`
+ vatCode (string)
+ fiscalCode (string)
+ companyName (string)

## Profile Address Base (Profile Address Partial Base)
+ address: `Piazza Dergano 3` (required, string)
+ description: `Address 1` (string)
+ type: billing (enum)

## Address1 (Profile Address Partial Base)
+ id: 1 (required, number) - ID of the address
+ type: postal (enum)
+ address: `Piazza Dergano 3` (required, string)
+ description: `Address 1` (string)
+ firstName:  `Mario1` - If address is postal, this is the recipient name
+ lastName: `Rossi1`  - If address is postal, this is the recipient surname
+ email: `testEmail1@test.com` - If address is postal, this is the recipient email

## Address2 (Profile Address Partial Base)
+ id: 2 (required, number) - ID of the address
+ type: billing  (enum)
+ address: `Viale Torino 10` (required, string)
+ description: `Address 2` (string)
+ firstName:  `Mario2` - If address is postal, this is the recipient name
+ lastName: `Rossi2`  - If address is postal, this is the recipient surname
+ email: `testEmail2@test.com` - If address is postal, this is the recipient email

## Address3 (Profile Address Partial Base)
+ id: 3 (required, number) - ID of the address
+ type: postalBilling
+ address: `Piazza Italia 2` (required, string)
+ description: `Address 3` (string)
+ firstName:  `Mario3` - If address is postal, this is the recipient name
+ lastName: `Rossi3`  - If address is postal, this is the recipient surname
+ email: `testEmail3@test.com` - If address is postal, this is the recipient email

## Profile Address Create (Address1)

## Profile Address Update (Address1)

## Selection (object)
+ type: serramenti (required, string) - type of the selection
+ sku: 1 (required, string) - the product commerce SKU for which the quote is being prepared
+ attributes: `{"color": "black", "isolation": "high"}` (object) - an object of attributes selected on the product. An attribute is represented as a key/value pair.

    + Properties
        + color: black
        + isolation: high
        + material: wood
        + attribute4: value4

+ alternate_products: `["2", "3"]` (array) - an array of alternative products (recommended by commerce). Each string is a commerce SKU.

    + Items
        + 2
        + 3

+ alternate_selections: `["3", "4"]` (array) - an array of alternative products selected by the user to be seen in the augmented reality.

    + Items
        + 3
        + 4

## Selection Write (Selection)


## Document Base (object)
+ userId: 1 (number) - ID of the user owning the document
+ type: order (required, enum) - type of the document
    + Members
        + order
        + quote
+ description: quote for beach house (string) - description of the document
+ formats: `["xml", "pdf"]` (array) - list of available file formats
    + Items
        + xml
        + pdf
+ status (enum[string]) - current status of the document
    + Members
        + proposal
        + confirmed
        + editable - if the document can be still modified or has been frozen

+ expiry (string) - Date representing validity of the document
+ documentReference: 3 (string) - reference to another Document (e.g. quote from which an order originated)
+ documentCode: 1 (string) - fpDealerID in case of document of type `quote`

## Document Create (Document Base)

## Document Read (Document)
+ status_hist (required, object) - past statuses of the document
    + Properties
       + *20150501*: proposal
       + *20150508*: confirmed

## Document Update (Document)

## Document File Base (object)
+ format: pdf (required, string) - format of the file with which we're interacting
+ file: `a2F3YWlpIGRvY3VtZW50Cg==` (required, string) - serialized stream representing the file.
+ url: `https://www.vlp.it/document/id` (required, string) - url of the file

## Document File Create (Document File Base)

## Document File Update (Document File)

## Event Partial Base (object)
+ userId: 1 (number) - ID of the user associated with the event
+ value: `-1` (number) - value of the event (only valid for event of type `vote` and `desire`)
+ description: `Descrizione storia` (required, string)
+ url: `https://www.vlp.com/wps/portal/stories/storia/1` (required, string)
+ timestamp: 546757636535 (number) - date of the event expressed as number of seconds since the Epoch.
+ zone: Milano (string) - position shared by the user
+ contentType: story (enum) - type of the content connected to this event.
    + story
    + product
+ sku: `012sku` (string) - sku of product

## Event1 (Event Partial Base)
+ id: 1 (number)
+ contentId: 1
+ type: vote
+ title: `Storia 1` (required, string)
+ imageUrl: `http://lnx.flushyourlife.com/voilap/dist/images/like-dislike/storia-like-01.jpg` (required, string)

## Event2 (Event Partial Base)
+ id: 2 (number)
+ contentId: 2
+ type: desire
+ title: `Storia 2` (required, string)
+ imageUrl: `http://lnx.flushyourlife.com/voilap/dist/images/like-dislike/storia-like-02.jpg` (required, string)

## Event3 (Event Partial Base)
+ id: 3 (number)
+ contentId: 3
+ type: view
+ title: `Storia 3` (required, string)
+ imageUrl: `http://lnx.flushyourlife.com/voilap/dist/images/like-dislike/storia-like-03.jpg` (required, string)

## Event Base (Event Partial Base)
+ contentId: 1 (required, string) - ID of the content for which the event is being recorded
+ type: vote (required, enum) - type of event
    + view
    + vote
    + desire
+ title: `Storia 1` (required, string)
+ imageUrl: `http://lnx.flushyourlife.com/voilap/dist/images/like-dislike/storia-like-01.jpg` (required, string)

## Event Create (Event Base)

## Event Update (Event)

## Product Base (object)
+ default_set: kitchen (required, string) - default set that will be copied in order to create a new scene for the specified object
+ availability: true (required, boolean)
+ assets (array[Asset Base]) - array of asset bundles

## Product Create (Product Base)

## Product Update (Product)

## Product Image (object)
+ type: main (required, enum) - type of the image.
    + Members
        + main
        + banner
        + carousel
        + details
+ productId: 1 (required, number) - SKU on the product repository.
+ index: 1 (number) - for image lists (e.g. carousels) the index of the image.
+ file: `a2F3YWlpIGRvY3VtZW50Cg==` (required, string) - serialized stream representing the image.

## Product Image Write (Product Image)


## Asset Base (object)
+ name: name (string) - name of the asset bundle.
+ type: model (enum) - type of the asset bundle
    + Members
        + model
        + finishing
        + part
+ layer (string)

## Asset Write (Asset Base)
+ file: `a2F3YWlpIGRvY3VtZW50Cg==` (required, string) - serialized stream representing the image.


## Scene Base (object)
+ description: `Scene description` (required, string)
+ userId: 1 (number) - ID of the user owning the scene. May be null for default scenes.
+ height: 10.57 (number)
+ width: 60.24 (number)
+ length: 14.2 (number)
+ sceneType (enum) - User specified type of the scene.
    + Members
        + `kitchen`
        + `livingroom`
+ set (string)
+ time (string)
+ weather (string)
+ season (string)
+ sound (string) - url of sound file **TODO: move to its own resource**

## Scene Create (Scene Base)

## Scene Update (Scene)

## Object Base (object)
+ sceneId (string) - ID of the associated scene, if present
+ objectId: 6 (string) - Identifier of the object in 3D Viewer
+ productId: 5 (string)
+ category (string)
+ type (string)
+ x: 10.6 (number) - position of the object on X axis
+ y: 1.6 (number) - position of the object on Y axis
+ z: 5.6 (number) - position of the object on Z axis.
+ rx: 100.6 (number) - rotation of the object on X axis.
+ ry: 10.6 (number) - rotation of the object on Y axis.
+ rz: 50.6 (number) - rotation of the object on Z axis.
+ s: 3 (number) - object scaling.

## Object Create (Object Base)

## Object Update (Object)

## Surface Base (object)
+ sceneId: 1 (required, number) - ID of the scene owning the surface.
+ surfaceId: 5 (string) - ID of the surface in the 3D viewer.
+ materialId: 3 (string)

## Surface Create (Surface Base)

## Surface Update (Surface)


## Contact Base (object)
+ userId: 1 (number) - ID of the user associated with the contact request
+ addressId: 1 (number) - ID of the address associated with the contact request
+ description: `Hi, please contact me` (string)
+ reason (enum)
+ date: `2015-05-01` (string)
+ timestamp: 123451325 (number) - date of the event expressed as number of seconds since the Epoch.
+ timeZone (string) - user range availabilty
+ note: `Hi, please contact me` (string)
- status (enum) - status of contact request (completed, pending)
    + `completed`
    + `pending`

## Contact Create (Contact Base)

## Contact Update (Contact)

## Wishlist Group Partial (object)
+ userId: 1 (required, number) - ID of the user associated with the wishlist group.

## Wishlist Group Base (Wishlist Group Partial)
+ groupName: `Per le vacanze` (string) - Name of the wishlist group.

## Wishlist1 (Wishlist Group Partial)
+ id: 1
+ groupName: `Per le vacanze` (string) - Name of the wishlist group.

## Wishlist2 (Wishlist Group Partial)
+ id: 2
+ groupName: `Da comprare` (string) - Name of the wishlist group.

## Wishlist3 (Wishlist Group Partial)
+ id: 3
+ groupName: `Divertente` (string) - Name of the wishlist group.

## Wishlist Group Create (Wishlist Group Base)

## Wishlist Group Update (Wishlist Group)

## Wishlist Group Event Base (object)
+ id: 124 (required, number) - ID of the event associated with the current group.

## Wishlist Group Event Create (Wishlist Group Event Base)

## Wishlist Group Event Update (Wishlist Group Event)
