FORMAT: 1A
HOST: https://webapps.vlp.com/

# VLP v1

Service Oriented Architecture specified for the VLP project.

# VLP [/]

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

Dates are always specified as `yyyy-mm-dd`, times as `HH:mm:ss:SSS`, according to
[Java SimpleDateFormat](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html).

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "profile_url": "/profiles",
            "selections_url": "/selections/my",
            "events_url": "/events",
            "products_url": "/products",
            "documents_url": "/documents",
            "ar_url": "/ar",
            "contacts_url": "/contacts"
        }

+ Response 500
    Returned when a generic error occours.

    + Body




#######################
# Group IS01 - Profiles
#######################

Resources related to user's profile in the API.

## Profiles collections [/profiles{?consultantId}{?page}{?backends}]

+ Attributes (Collection)
  + profiles (array[Profile]) - array of user accessible profiles

### List Profiles [GET]
List user profiles. This can be sliced and filtered in order to return only
profiles associated with a given `consultantId`.

+ Parameters
    + page: 1 (optional, number) - The page of profiles to return
    + consultantId: 1 (optional, number) - ID of the consultant associated with this user
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)

    + Headers

            Link: </profiles?page=2>; rel="next"

    + Attributes (Profiles collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Profile [POST]
Create a user profile.


+ Request (application/json)
    + Attributes (Profile Create)

+ Response 201

    + Headers

            Location: /profiles/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Profile [/profiles/{id}{?backends}]

+ Parameters
    + id: 1 (required, number) - ID of the user

+ Attributes (Profile Base)
    + id: 1 (required, number) - ID of the user profile

### Read Profile [GET]

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)

    + Attributes (Profile)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Profile [PUT]

+ Request (application/json)

    + Attributes (Profile Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Profile [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204


+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## User personal profile [/profiles/my{?backends}]

Used to retrieve user personal details.

### Read Profile [GET]

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)
  + Attributes (Profile)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Profile Addresses collections [/profiles/{userId}/addresses{?page}{?backends}]

+ Attributes
  + count: 1 (number) - total number of addresses
  + addresses (array[Profile Address]) - array of user addresses

### List Profile Addresses [GET]

+ Parameters
  + userId: 1 (required, number) - ID of the user
  + page: 1 (optional, number) - The page of addresses to return
  + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
      + Members
          + cache
          + db
          + ldap
          + connections
          + commerce

+ Response 200 (application/json)

      + Headers

              Link: </profiles/1/addresses?page=2>; rel="next"

      + Attributes (Profile Addresses collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Profile Address [POST]

+ Request (application/json)
    + Attribute (Profile Address Create)

+ Response 201

    + Headers

            Location: /profiles/1/addresses/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Profile Address [/profiles/{userId}/addresses/{id}{?backends}]

+ Parameters
    + userId: 1 (number) - ID of the user
    + id: 1 (number) - ID of the address

+ Attributes (Profile Address Base)
    + id: 1 (required, number) - ID of the address

### Read Profile Address [GET]

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)

    + Attributes (Profile Address)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Profile Address [PUT]

+ Request (application/json)

    + Attributes (Profile Address Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Profile Address [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



#########################
# Group IS15 – Selections
#########################

Resources related to user's selected products.
An user can list its selected products, create a selection for his session and then edit it.

**Note**: Only one product per category (e.g. serramenti, pavimenti) can be selected
at a given time. If another product of the same category is selected, it will replace
the currently selected product.

## Selections collections [/selections/{userId}]

The following methods allow the user to interact with selected products.

+ Parameters
    + userId: 1 (number) - ID of the user owning the selections

+ Attributes
    + userId: 1 (number) - ID of the user owning the selections
    + selections (array[Selection]) - selections perfomed by the user

### List Selections [GET]

This action retrieves the list of selected products.

+ Response 200 (application/json)

    + Attributes (Selections collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Selection [POST]

This action is used to create a new selection in the user's selection object.
It will replace his current selection if he already has one in the same category.

+ Request (application/json)

  + Attributes (Selection Write)

+ Response 201

    + Headers

            Location: /selections/{userId}/serramenti

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Selection [/selections/{userId}/{type}]

These actions operate on the selection of the required `type`.

+ Parameters
    + userId: 1 (number) - ID of the user owning the selections
    + type: serramenti (string) - type of selection to operate on. Each selection is a category (e.g. "serramenti", "pavimenti").

### Read Selection [GET]

+ Response 200 (application/json)

    + Attributes (Selection)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Selection [PUT]

+ Request (application/json)

    + Attributes (Selection Write)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Selection [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


########################
# Group IS03 - Documents
########################

Resources related to user's documents in the API.
An user can list its previous documents, create a document and then edit it.

Document acts as a "super-class" for quotes and orders.

## Documents collections [/documents{?userId}{?page}{?type}{?backends}]

The following methods allow the user to interact with documents.

+ Attributes (Collection)
    + documents (array[Document]) - array of documents accessible by the user

### List Documents [GET]

This action retrieves the list of documents accessible by the user,
possibly sliced and filtered only for the specified `userId` and/or `type`.

+ Parameters
    + userId: 1 (optional, number) - Filter documents created by the specified `userId`.
    + page: 1 (optional, number) - The page of documents to return.
    + type: quote (optional, enum[string]) - Filter only specified type of document.
        + Members
            + quote
            + order
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)

    + Headers

            Link: </documents?page=2>; rel="next"

    + Attributes (Documents collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Document [POST]

This method allows the user to create a new document.

If no `userId` is given, it is assumed that the document is created for the current user.

**Note**: the returned `Location` header points to the created document ID,
not the given FP Dealer ID.

+ Request (application/json)
    + Attributes (Document Create)

+ Response 201

    + Headers

            Location: /documents/2

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Document [/documents/{id}{?backends}]

+ Parameters
    + id: 1 (required, string) - ID of the document

+ Attributes (Document Base)
    + id: 1 (required, number) - ID of the document

### Read Document [GET]

See the details of a given document. This returns the single document
istances with its historic statuses.

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)

    + Attributes (Document Read)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Document [PUT]

This action allows the user to change an existing document.

**Note**: When the current status of a document is changed, its historic
statuses will have to be recorded. Manual changes on historic statuses are not
supported.

+ Request (application/json)
    + Attributes (Document Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Document [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Document Files collections [/documtents/{id}/files]

### Create Document File [POST]

This actions allow adding a new file to an existing document.

+ Request (application/json)
    + Attributes (Document File Create)

+ Response 201

    + Headers

            Location: /documents/2/files/pdf

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Document File [/documents/{id}/files/{format}{?backends}]

API route for interacting with documents' files.

Create and update actions expect the file stream as input.

**Note**: when the available files change (CD actions) also the available
`formats` field on the document will get updated.

+ Parameters
    + id: 1 (required, string) - ID of the document
    + format: pdf (required, string) - format of the file with which we're interacting

+ Attributes (Document File Base)
    + id: 1 (required, number) - ID of the document

### Read Document File [GET]
Retrieve the document (file stream).

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/stream)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Document File [PUT]

+ Request (application/json)
    + Attributes (Document File Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Document File [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



#####################
# Group IS12 - Events
#####################

## Events collections [/events{?userId}{?page}{?type}{?backends}]

+ Attributes (Collection)
    + events (array[Event]) - array of returned events

### List Events [GET]

Retrive content (e.g. stories, products) events, possibly filtered by `userId`
and/or `type` and sliced.

+ Parameters
    + userId: 1 (optional, number) - Filter events created by the specified user
    + type: vote (enum[string]) - Filter only specified type of event
        + Members
            + view - content visualization
            + vote - content up or down vote
            + desire - content desired
    + page: 1 (optional, number) - The page of events to return
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Request Single like event (application/json)

+ Response 200 (application/json)

    + Headers

            Link: </events?page=2>; rel="next"

    + Attributes (Events collections)


+ Request Multiple Like events (application/json)

    + Headers

            Multi: true

+ Response 200 (application/json)

    Response with multiple like events.

    + Headers

            Link: </events?page=2>; rel="next"

    + Attributes (Collection)
        + events (array[Like1, Like2])

+ Response 500
    Returned when a generic error occours.

    + Body

### Find Events [GET /events/find{?contentId}{?backends}]

Action that can be used to find the events in the repository starting
from a contentId.

Action return an array that contains all events linked at contentId.

+ Parameters
    + contentId: 1 (string) - ID of the content
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)
    + Attributes (Events collections)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Upsert Event [POST /events/upsert]

Action that can be used to insert and/or update the events in the repository associated
at a contentId.

If the event not exists it'll created, else it'll be updated

+ Request (application/json)
    + Attribute (Event Create)

+ Response 201

    + Headers

            Location: /events/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Event [POST]

+ Request (application/json)
    + Attribute (Event Create)

+ Response 201

    + Headers

            Location: /events/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Event [/events/{id}{?backends}]

+ Attribute (Event Base)
    + id: 1 (required, number) - ID of the event

+ Parameters
    + id: 1 (required, string) - ID of the event

### Read Event [GET]

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)
    + Attributes (Event)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Event [PUT]

Updating an "event" is a weird idea. Yet it makes sense when an event is
intended as a user action (e.g. like/dislike). For instance, a user can first
like a content (creating an event on the specified content) and then dislike it,
updating his previous event.

+ Request (application/json)
    + Attributes (Event Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Event [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



#######################
# Group IS17 - Products
#######################

API group used to handle products.

## Products collections [/products]

+ Attributes (Collection)
    + products (array[Product]) - array of products accessible by the user

### Find products [GET /find{?commerceSKU}{?attributes}{?backends}]

Action that can be used to find a product in the repository starting
from the commerce SKU and the selections (map of attributes).

This action can be used to retrieve the Product repository ID that can later be used to
retrieve images and renderings.

Only one Product is exptected to be returned, but for consistency with other
collection actions we return an array.

+ Parameters
    + commerceSKU: 1 (string) - SKU on the commerce
    + attributes: {"color": "black", "isolation": "high", "material": "wood"} (object) -
      attribute selection on the commerce SKU product
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)
    + Attributes (Products collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Product [POST]

+ Request (application/json)
    + Attribute (Product Create)

+ Response 201

    + Headers

            Location: /products/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Product [/products/{id}{?backends}]

+ Attributes (Product Base)
    + id: 5 (required, string) - SKU of the product in the product repository

+ Parameters
    + id: 5 (required, string) - SKU of the product

### Read Product [GET]

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)
    + Attributes (Product)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Product [PUT]

+ Request (application/json)
    + Attributes (Product Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Product [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

#############################
# Group IS02 - Product Images
#############################

Sub-resource of a product resource. First find the product SKU, then interact
with its images.

## Product Images collections [/products/{productId}/images]

+ Parameters
    + productId: 1 (required, number) - SKU on the product repository


### Create Product Image [POST]

+ Request (application/json)

    + Attributes (Product Image Write)

+ Response 201

    + Headers

            Location: /products/{productId}/images/main

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


## Product Image [/products/{productId}/images/{type}/{?index}{?backends}]

+ Parameters
    + type: main (required, enum[string]) - type of the image being required.
        + Members
            + main
            + banner
            + carousel
            + details
    + productId: 1 (required, string) - SKU on the product repository.
    + index: 1 (number) - for image lists (e.g. carousels) the index of the image.

### Read Product Image [GET]
Retrieve the image (file stream).

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (image/png)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


### Update Product Image [PUT]

+ Request (application/json)
    + Attributes(Product Image Write)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Product Image [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



############################
# Group IS08 - Asset Bundles
############################

Assets used in the 3D viewer application. An asset is ultimately a file,
identified by the pair (`type`, `name`). Assets are used to represent static
resources in the 3D Viewer, such as models, finishings and parts of products,
surfaces and scenes.

## Asset Collections [/assets]

### Create Asset [POST]

+ Request (application/json)
    + Attributes (Asset Write)

+ Response 201

    + Headers

            Location: /assets/model/name

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Asset [/assets/{type}/{name}{?backends}]

+ Parameters
    + type: model (enum) - type of the asset bundle
        + Members
            + model
            + finishing
            + part
    + name (string) - name of the asset bundle

+ Attributes (Asset Base)

### Read Asset [GET]
Retrieve the image (file stream).

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/png)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Asset [PUT]

+ Request (application/json)
    + Attributes (Asset Write)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Asset [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


#################
# Group IS09 - 3D
#################

API group used to handle objects managed by the augmented reality 3D viewer.

The main resources managed are:

+ `Object`, an object rendered in a 3D environment
+ `Scene`, a 3D environment consisting of multiple objects
+ `Surface`

## Scenes collections [/ar/scenes{?userId}{?page}{?backends}]

+ Attributes (Collection)
    + scenes (array[Scene]) - array of scenes accessible by the user

### List Scenes [GET]

+ Parameters
    + userId: 1 (optional, number) - filter scenes for the specified user
    + page: 1 (optional, number) - slice scenes
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)

    + Attributes (Scenes collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Copy Scene from set [POST /ar/scenes/copy]

This action creates a new scene copying an existing set (scene template). In then
proceeds to create a new Scene Object for the specified productId and associates
it with the newly created scene.

+ Request (application/json)
    + Attributes
        + productId (required, number) - SKU of the product in the repository
        + default_set (required, string)

+ Response 201

    + Headers

            Location: /ar/scenes/1

### Create Scene [POST]

+ Request (application/json)
    + Attributes (Scene Create)

+ Response 201

    + Headers

            Location: /ar/scenes/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Scene [/ar/scenes/{id}{?backends}]

+ Attributes (Scene Base)
    + id: 1 (required, string) - ID of the scene.

+ Parameters
    + id: 1 (string) - ID of the scene.

### Read Scene [GET]

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)

    + Attributes (Scene)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Scene [PUT]

+ Request (application/json)

    + Attributes (Scene Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Scene [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Objects collections [/ar/scenes/{sceneId}/objects{?page}{?backends}]

+ Attributes (Collection)
    + objects (array[Object]) - array of objects accessible by the user

+ Parameters
    + sceneId: 1 (string) - scene owning the objects

### List Objects [GET]

+ Parameters
    + page: 1 (optional, number) - slice scene objects
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)
    + Attributes (Objects collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Object [POST]
Create a new Object. If `sceneId` is specified, it is implied that the object
will also be "added" to the scene.

+ Request (application/json)
    + Attributes (Object Create)

+ Response 201

    + Headers

            Location: /ar/objects/3

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Object [/ar/scenes/{sceneId}/{id}{?backends}]

+ Attributes (Object Base)
    + id: 1 (required, string)

+ Parameters
    + id: 1 (string) - ID of the object
    + sceneId: 1 (string) - scene owning the objects

### Read Object [GET]

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)

    + Attributes (Object)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Object [PUT]

+ Request (application/json)

    + Attributes (Object Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Object [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


## Surfaces collections [/ar/scenes/{sceneId}/surfaces{?page}{?backends}]

+ Attributes (Collection)
    + surfaces (array[Surface]) - array of surfaces accessible by the user

### List Surfaces [GET]

+ Parameters
    + sceneId: 5 (required, number) - ID scene
    + page: 1 (number) - slice surfaces
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce


+ Response 200 (application/json)

    + Headers

            Link: </ar/scenes/1/surfaces?page=2>; rel="next"

    + Attributes (Surfaces collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Surface [POST]

+ Request (application/json)
    + Attribute (Surface Create)

+ Response 201

    + Headers

            Location: /ar/scenes/1/surfaces/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Surface [/ar/scenes/{sceneId}/surfaces/{id}{?backends}]

+ Attributes (Surface Base)
    + id: 1 (number) - ID of the surface

+ Parameters
    + sceneId: 5 (required, number) - ID scene
    + id: 1 (required, string) - ID of the surface

### Read Surface [GET]

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)
    + Attribute (Surface)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Surface [PUT]

+ Request (application/json)
    + Attribute (Surface Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Surface [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



###############################
# Group IS07 - Contact Requests
###############################

API group used to handle users' contact requests.

## Contacts collections [/contacts{?userId}{?page}{?backends}]

+ Attributes (Collection)
  + contacts (array[Contact]) - array of contact requests accessible by the user

### List Contacts [GET]

+ Parameters
    + userId: 1 (optional, string) - filter contact requests for the specified user
    + page: 1 (optional, number) - slice contact requests
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce


+ Response 200 (application/json)
    + Attributes (Contacts collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Contact [POST]

+ Request (application/json)
    + Attributes (Contact Create)

+ Response 201

    + Headers

            Location: /contacts/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Contact [/contacts/{id}{?backends}]

+ Parameters
    + id: 1 (required, string) - ID of the contact request with which interact

+ Attributes (Contact Base)
    + id: 1 (required, number)

### Read Contact [GET]

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)
    + Attributes (Contact)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Contact [PUT]

+ Request (application/json)
    + Attributes (Contact Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Contact [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



##############################
# Group IS18 - Wishlist Groups
##############################

API group used to handle groups of wishlists.

## Wishlist Groups collections [/wishlists]

+ Attributes (Collection)
    + wishlists (array[Wishlist Group]) - array of wishlist groups accessible by the user

### List Wishlist Groups [GET /wishlists{?userId}{?page}{?backends}]

This action retrieves the list of wishlists groups accessible by the user,
possibly sliced and filtered only for the specified `userId`.

+ Parameters
    + userId: 1 (optional, number) - Filter wishlist groups created by the specified `userId`.
    + page: 1 (optional, number) - The page of wishlist groups to return.
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)
    + Attributes (Wishlist Groups collections)

+ Response 500
    Returned when a generic error occours.

    + Body

### Create Wishlist Group [POST]

+ Request (application/json)
    + Attribute (Wishlist Group Create)

+ Response 201

    + Headers

            Location: /wishlists/1

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Wishlist Group [/wishlists/{id}{?backends}]

+ Attributes (Wishlist Group Base)
    + id: 5 (required, string) - id of the wishlist group

+ Parameters
    + id: 5 (required, string) - id of the wishlist group

### Read Wishlist Group [GET]

+ Parameters
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce

+ Response 200 (application/json)
    + Attributes (Wishlist Group)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Wishlist Group [PUT]

+ Request (application/json)
    + Attributes (Wishlist Group Update)

+ Response 200

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Wishlist Group [DELETE]

+ Request (application/json)
    + Attributes (Delete Base)

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## Wishlist Group Events [/wishlists/{id}/events{?backends}]

+ Attributes (Collection)
    + events (array[Event]) - array of `desire` events associated with the given wishlist

### List Wishlist Group Events [GET]

This action retrieves the events of type `desire` associated with the given
wishlist group id.

+ Parameters
    + id: 5 (required, string) - id of the wishlist group
    + backends: cache (optional, enum) - From which backends the resource should be read from. This parameter can be repeated with different values.
        + Members
            + cache
            + db
            + ldap
            + connections
            + commerce


+ Response 200 (application/json)

    + Attributes (Wishlist Group Events)
        + type: desire


# Data Structures

## Write Base (object)
+ backends: `{"cache": true, "db": true}` (required, object) - to which backends the resource is being saved to.
    + Properties
        + cache: true (boolean)
        + db: true (boolean)
        + ldap (boolean)
        + connections (boolean)
        + commerce (boolean)

## Delete Base (object)
+ backends: `{"cache": true, "db": true}` (required, object) - to which backends the resource is being deleted from.
    + Properties
        + cache: true (boolean)
        + db: true (boolean)
        + ldap (boolean)
        + connections (boolean)
        + commerce (boolean)

## Collection (object)
+ count: 1 (number) - total number of resources that can be accessed by the user

## Profile Base (object)
+ consultantId: 1 (number) - ID of the consultant associated with this user
+ email: `v.ponte@wintech.it` (required, string)
+ username: `v.ponte@wintech.it` (string) - the field isn't null when user is registered and validated
+ firstName: Valerio (string)
+ lastName: Ponte (string)
+ phoneNumber: `0039-3401004285` (string) - A string with the following format: `<4 digits country code>-<phone number>`
+ imageUrl: `https://www.vlp.com/logo.png` (string) - user profile image
+ description (string)
+ area: Milano (string) - position shared by the user
+ address (string) - Main user address
+ city (string) - Main user addresss
+ status (enum) - Whether the user activated the account or not
    + active
    + inactive

## Profile Create (Profile Base)
+ Include Write Base

## Profile Update (Profile)
+ Include Write Base

## Profile Address Base (object)
+ userId: 1 (required, number) - ID of the user owning this address
+ type: billing (required, enum[string])
    + postal
    + billing
    + postalBilling
+ description: `My home address` (string)
+ address: `Piazza Dergano 9` (required, string)
+ zipCode: 20158 (required, number)
+ city: Milano (required, string)
+ country: Italia (required, string)
+ phoneNumber: `0039-3401004285` (string) - A string with the following format: `<4 digits country code>-<phone number>`
+ vatCode (string)
+ fiscalCode (string)
+ companyName (string)
+ firstName (string) - If address is postal, this is the recipient name
+ lastName (string) - If address is postal, this is the recipient surname
+ email (string) - If address is postal, this is the recipient email

## Profile Address Create (Profile Address Base)
+ Include Write Base

## Profile Address Update (Profile Address)
+ Include Write Base


## Selection (object)
+ type: serramenti (required, string) - type of the selection
+ sku: 1 (required, string) - the product commerce SKU for which the quote is being prepared
+ attributes: `{"color": "black", "isolation": "high"}` (object) - an object of attributes selected on the product. An attribute is represented as a key/value pair.

    + Properties
        + color: black
        + isolation: high
        + material: wood
        + attribute4: value4

+ alternate_products: `["2", "3"]` (array) - an array of alternative products (recommended by commerce). Each string is a commerce SKU.

    + Items
        + 2
        + 3

+ alternate_selections: `["3", "4"]` (array) - an array of alternative products selected by the user to be seen in the augmented reality.

    + Items
        + 3
        + 4

## Selection Write (Selection)
+ Include Write Base


## Document Base (object)
+ userId: 1 (number) - ID of the user owning the document
+ type: order (required, enum) - type of the document
    + Members
        + order
        + quote
+ formats: `["xml", "pdf"]` (array) - list of available file formats
    + Items
        + xml
        + pdf
+ status (enum[string]) - current status of the document
    + Members
        + proposal
        + confirmed
        + editable - if the document can be still modified or has been frozen

+ expiry (string) - Date representing validity of the document
+ documentReference: 3 (string) - reference to another Document (e.g. quote from which an order originated)
+ documentCode: 1 (string) - fpDealerID in case of document of type `quote`

## Document Create (Document Base)
+ Include Write Base

## Document Read (Document)
+ status_hist (required, object) - past statuses of the document
    + Properties
       + *20150501*: proposal
       + *20150508*: confirmed

## Document Update (Document)
+ Include Write Base

## Document File Base (object)
+ format: pdf (required, string) - format of the file with which we're interacting
+ file: `a2F3YWlpIGRvY3VtZW50Cg==` (required, string) - serialized stream representing the file.
+ url: `https://www.vlp.it/document/id` (required, string) - url of the file

## Document File Create (Document File Base)
+ Include Write Base

## Document File Update (Document File)
+ Include Write Base

## Like1 (Event Base)
+ id: 1

## Like2 (Event Base)
+ id: 2

## Event Base (object)
+ userId: 1 (number) - ID of the user associated with the event
+ contentId: 1 (required, string) - ID of the content for which the event is being recorded
+ type: vote (required, enum) - type of event
    + view
    + vote
    + desire
+ value: `-1` (number) - value of the event (only valid for event of type `vote`)
+ title: `Storia 1` (required, string)
+ URL: `https://www.vlp.com/wps/portal/stories/storia/1` (required, string)
+ image_URL: `https://www.vlp.com/logo.png` (required, string)
+ timestamp: 546757636535 (number) - date of the event expressed as number of seconds since the Epoch.
+ zone: Milano (string) - position shared by the user

## Event Create (Event Base)
+ Include Write Base

## Event Update (Event)
+ Include Write Base

## Product Base (object)
+ default_set: kitchen (required, string) - default set that will be copied in order to create a new scene for the specified object
+ availability: true (required, boolean)
+ assets (array[Asset Base]) - array of asset bundles

## Product Create (Product Base)
+ Include Write Base

## Product Update (Product)
+ Include Write Base

## Product Image (object)
+ type: main (required, enum) - type of the image.
    + Members
        + main
        + banner
        + carousel
        + details
+ productId: 1 (required, number) - SKU on the product repository.
+ index: 1 (number) - for image lists (e.g. carousels) the index of the image.
+ file: `a2F3YWlpIGRvY3VtZW50Cg==` (required, string) - serialized stream representing the image.

## Product Image Write (Product Image)
+ Include Write Base


## Asset Base (object)
+ name: name (string) - name of the asset bundle.
+ type: model (enum) - type of the asset bundle
    + Members
        + model
        + finishing
        + part
+ layer (string)

## Asset Write (Asset Base)
+ Include Write Base
+ file: `a2F3YWlpIGRvY3VtZW50Cg==` (required, string) - serialized stream representing the image.


## Scene Base (object)
+ description: `Scene description` (required, string)
+ userId: 1 (number) - ID of the user owning the scene. May be null for default scenes.
+ height: 10.57 (number)
+ width: 60.24 (number)
+ length: 14.2 (number)
+ sceneType (enum) - User specified type of the scene.
    + Members
        + `kitchen`
        + `livingroom`
+ set (string)
+ time (string)
+ weather (string)
+ season (string)
+ sound (string) - url of sound file **TODO: move to its own resource**

## Scene Create (Scene Base)
+ Include Write Base

## Scene Update (Scene)
+ Include Write Base

## Object Base (object)
+ sceneId (string) - ID of the associated scene, if present
+ objectId: 6 (string) - Identifier of the object in 3D Viewer
+ productId: 5 (string)
+ category (string)
+ type (string)
+ x: 10.6 (number) - position of the object on X axis
+ y: 1.6 (number) - position of the object on Y axis
+ z: 5.6 (number) - position of the object on Z axis.
+ rx: 100.6 (number) - rotation of the object on X axis.
+ ry: 10.6 (number) - rotation of the object on Y axis.
+ rz: 50.6 (number) - rotation of the object on Z axis.
+ s: 3 (number) - object scaling.

## Object Create (Object Base)
+ Include Write Base

## Object Update (Object)
+ Include Write Base

## Surface Base (object)
+ sceneId: 1 (required, number) - ID of the scene owning the surface.
+ surfaceId: 5 (string) - ID of the surface in the 3D viewer.
+ materialId: 3 (string)

## Surface Create (Surface Base)
+ Include Write Base

## Surface Update (Surface)
+ Include Write Base


## Contact Base (object)
+ userId: 1 (number) - ID of the user associated with the contact request
+ addressId: 1 (number) - ID of the address associated with the contact request
+ description: `Hi, please contact me` (string)
+ reason (enum)
+ date: `2015-05-01` (string)
+ timestamp: 123451325 (number) - date of the event expressed as number of seconds since the Epoch.
+ timeZone (string) - user range availabilty
+ note: `Hi, please contact me` (string)
- status (enum) - status of contact request (completed, pending)
    + `completed`
    + `pending`

## Contact Create (Contact Base)
+ Include Write Base

## Contact Update (Contact)
+ Include Write Base

## Wishlist Group Base (object)
+ userId: 1 (required, number) - ID of the user associated with the wishlist group.
+ groupName: `Per le vacanze` (string) - Name of the wishlist group.

## Wishlist Group Create (Contact Base)
+ Include Write Base

## Wishlist Group Update (Contact)
+ Include Write Base
